server:
  port: 9006
spring:
  application:
    name: zuul
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://user:password@127.0.0.1:10001/eureka/
zuul:
  routes:
    application:
      serviceId: application
  host:
    #zuul配置route-url时生效
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
ribbon:
  # 配置routr-serviceId生效
  ConnectTimeout: 60000
  ReadTimeout: 60000
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  level:
    com.netflix: ERROR

