server:
  port: 10001
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@127.0.0.1:10001/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 15000
spring:
  application:
    name: eureka
  security:
    user:
      name: user
      password: password
logging:
  level:
    com.netflix: ERROR